:patches:
  :WebcamMesh:
    :node_map:
      2: 1
      1: 3
    :action:
      - :name: FG Zoom
        :key: fgZoom
        :default:
          :scale: !ruby/range 0.1..10.0
          :value: 3
        :midi:
          :channel: 4
          :index: 0
          :scale: !ruby/range 1..127

      - :name: Z Depth
        :key: zDepth
        :default:
          :scale: !ruby/range 0..1000
          :value: 400
        :midi:
          :channel: 4
          :index: 1
          :scale: !ruby/range 1..127

      - :name: Noise Strength
        :key: noiseStrength
        :default:
          :scale: !ruby/range 0..600
          :value: 200
        :midi:
          :channel: 4
          :index: 2
          :scale: !ruby/range 1..127

      - :name: Noise Speed
        :key: noiseSpeed
        :default:
          :scale: !ruby/range 0..0.05
          :value: 0.01
        :midi:
          :channel: 4
          :index: 3
          :scale: !ruby/range 1..127

      - :name: Noise Scale
        :key: noiseScale
        :default:
          :scale: !ruby/range 0..0.1
          :value: 0.01
        :midi:
          :channel: 4
          :index: 4
          :scale: !ruby/range 1..127

      - :name: Hue
        :key: hue
        :default:
          :scale: !ruby/range 0..359
          :value: 0
        :midi:
          :channel: 4
          :index: 5
          :scale: !ruby/range 1..127

      - :name: Saturation
        :key: saturation
        :default:
          :scale: !ruby/range 1.0..10
          :value: 1
        :midi:
          :channel: 4
          :index: 6
          :scale: !ruby/range 1..127

      - :name: Key Color
        :key: keyColor
        :default:
          :scale: !ruby/range 2..16777215
          :value: 1
        :midi:
          :channel: 4
          :index: 7
          :scale: !ruby/range 1..127

      #- :name: Toggle Keyer
      #  :key: toggleKeyer
      #  :midi:
      #    :channel: 4
      #    :index: 8

      - :name: Mesh Opacity
        :key: mOpac
        :midi:
          :channel: 4
          :index: 9

      - :name: Wireframe Opacity
        :key: wfOpac
        :midi:
          :channel: 4
          :index: 10

      # - :name: Contrast
      #   :key: contrast
      #   :default:
      #     :scale: !ruby/range 0.5..5.0
      #     :value: 3
      #   :midi:
      #     :channel: 4
      #     :index: 10
      #     :scale: !ruby/range 1..127
      #
      # - :name: BG Zoom
      #   :key: bgZoom
      #   :default:
      #     :scale: !ruby/range 0.1..10.0
      #     :value: 3
      #   :midi:
      #     :channel: 4
      #     :index: 11
      #     :scale: !ruby/range 1..127
      #
      # - :name: BG Playback Rate
      #   :key: bgPlaybackRate
      #   :default:
      #     :scale: !ruby/range 0.01..2.0
      #     :value: 1
      #   :midi:
      #     :channel: 4
      #     :index: 12
      #     :scale: !ruby/range 1..127
      #
      # - :name: Audio Amount
      #   :key: audioAmount
      #   :default:
      #     :scale: !ruby/range 0..100
      #     :value: 100
      #   :midi:
      #     :channel: 4
      #     :index: 13
      #     :scale: !ruby/range 1..127
