:patches:
  :WebcamMesh:
    :node_map:
      2: 1
      1: 3
    :action:
      - :name: FG Zoom
        :key: fgZoom
        :default:
          :scale: !ruby/range 0.1..10.0
          :value: 3
        :midi:
          :channel: 0
          :index: 0

      - :name: Mesh Opacity
        :key: mOpac
        :default:
          :scale: !ruby/range 0..1.0
          :value: 1
        :midi:
          :channel: 0
          :index: 1

      - :name: Grid Opacity
        :key: wfOpac
        :default:
          :scale: !ruby/range 0..0.3
          :value: 0.1
        :midi:
          :channel: 0
          :index: 2

      - :name: Contrast
        :key: contrast
        :default:
          :scale: !ruby/range 0.5..5.0
          :value: 3
        :midi:
          :channel: 0
          :index: 3

      - :name: Z Depth
        :key: zDepth
        :default:
          :scale: !ruby/range 0..1000
          :value: 400
        :midi:
          :channel: 0
          :index: 4

      - :name: Noise Strength
        :key: noiseStrength
        :default:
          :scale: !ruby/range 0..600
          :value: 200
        :midi:
          :channel: 0
          :index: 5

      - :name: Noise Speed
        :key: noiseSpeed
        :default:
          :scale: !ruby/range 0..0.05
          :value: 0.01
        :midi:
          :channel: 0
          :index: 6

      - :name: Noise Scale
        :key: noiseScale
        :default:
          :scale: !ruby/range 0..0.1
          :value: 0.01
        :midi:
          :channel: 0
          :index: 7

      - :name: Invert Z
        :key: invertZ
        :default:
          :value: false
        :osc:
          :address: /1/toggleA_1

      - :name: Spin X
        :key: spin_x
        :default:
          :scale: !ruby/range 0..100
        :osc:
          :address: /multifaderM/1
          :scale: !ruby/range 0..1.0

      - :name: Spin Y
        :key: spin_y
        :default:
          :scale: !ruby/range 0..100
        :osc:
          :address: /multifaderM/2
          :scale: !ruby/range 0..1.0

      - :name: Spin Speed
        :key: spinSpeed
        :default:
          :scale: !ruby/range 0..0.002
        :osc:
          :address: /multifaderM/3
          :scale: !ruby/range 0..1.0

      - :name: Hue
        :key: hue
        :default:
          :scale: !ruby/range 0..359
          :value: 0
        :midi:
          :channel: 0
          :index: 8

      - :name: Saturation
        :key: saturation
        :default:
          :scale: !ruby/range 1.0..10
          :value: 1
        :midi:
          :channel: 0
          :index: 12

      - :name: Key Color
        :key: keyColor
        :default:
          :scale: !ruby/range 0..16777215
          :value: 1
        :midi:
          :channel: 0
          :index: 13

      - :name: Reset Rotation
        :key: resetRotation
        :osc:
          :address: /encoderM

      - :name: Audio Amount
        :key: audioAmount
        :default:
          :scale: !ruby/range 0..100
          :value: 100
        :midi:
          :channel: 0
          :index: 9

      - :name: BG Zoom
        :key: bgZoom
        :default:
          :scale: !ruby/range 0.1..10.0
          :value: 3
        :midi:
          :channel: 0
          :index: 10

      - :name: BG Playback Rate
        :key: bgPlaybackRate
        :default:
          :scale: !ruby/range 0.01..2.0
          :value: 1
        :midi:
          :channel: 0
          :index: 11

      - :name: Hue Rotation
        :key: hueRotation
