#!/usr/bin/env ruby
$:.unshift(File.join("lib"))

require "liveset"

@config = Liveset::Configuration.new

flags = "-nosession -newwin http://localhost:#{@config.vz[:server][:port]}"

`/Applications/Opera.app/Contents/MacOS/Opera #{flags} > log/opera.log 2>&1`
