#!/usr/bin/env ruby
$:.unshift(File.join("lib"))

require "liveset"
require "micromidi"

MESSAGES = [
  {
    :function => "Reset",
    :note => "F9"
  },
  {
    :function => "Shutdown",
    :note => "F#9"
  },
  {
    :function => "Reboot",
    :note => "G9"
  }
]

@outputs = UniMIDI::Output.all.map(&:open)

@config = Liveset::Configuration.new
@clips = @config.vidplayer[:clips].freeze
@channel = @config.vidplayer[:settings][:midi][:channel].freeze
actions = @clips + MESSAGES

loop do
  actions.each_with_index do |action, i|
    name = action[:file] || action[:function]
    puts "#{i+1}. #{name}"
  end
  print "> "
  choice = gets
  unless (index = choice.chomp.to_i - 1) == -1
    unless (action = actions[index]).nil?
      note = action[:note]
      if (name = action[:file])
        type = "clip"
      else
        name = action[:function]
        type = "function"
      end
      puts "Sending note #{note} for #{type} #{name}"
      message = MIDIMessage::NoteOn[note].new(@channel, 100)
      @output.each { |output| output.puts(*message.to_a) }
    end
  end
end
