#!/usr/bin/env ruby
$:.unshift(File.join("lib"))

require "liveset"
require "micromidi"

@output = UniMIDI::Output.gets

@config = Liveset::Configuration.new
@clips = @config.vidplayer[:clips].freeze
@channel = @config.vidplayer[:settings][:midi][:channel].freeze

loop do
  @clips.each_with_index do |clip, i|
    puts "#{i+1}. #{clip[:file]}"
  end
  print "> "
  choice = gets
  unless (index = choice.chomp.to_i - 1) == -1
    unless (clip = @clips[index]).nil?
      note = clip[:note]
      puts "Sending note #{note} for clip #{clip[:file]}"
      message = MIDIMessage::NoteOn[note].new(@channel, 100)
      @output.puts(*message.to_a)
    end
  end
end
