- :note: C0
  :file: spider.mov
- :note: D0
  :file: car.mov
- :note: E0
  :file: loop.mov
- :note: F0
  :file: bigbaby.mov
- :note: G0
  :file: swipe.mov
- :note: A0
  :file: kissing.mov
- :note: B0
  :file: kissing_comp.mov
- :note: C1
  :file: fish.mov
- :note: D1
  :file: horse.mov
- :note: E1
  :file: xylem.mov
- :note: B1
  :file: cavy.mov
- :note: D2
  :file: meatball.mov
- :note: F2
  :file: fern.mov
- :note: G2
  :file: dollar.mov
# Tail
- :note: A2
  :file: tail.mov
- :note: A#2
  :file: tail_2.mov
- :note: B2
  :file: tail_3.mov
# Exit Tone
- :note: C3
  :file: exit.mov
- :note: D3
  :file: exit_2.mov
- :note: E3
  :file: exit_3.mov
# Zishethe
- :note: G3
  :file: zishethe.mov
- :note: G#3
  :file: zishethe_2.mov
- :note: A3
  :file: zishethe_3.mov
- :note: B3
  :file: zishethe_4.mov
# PM Sink
- :note: C4
  :file: sink.mov
- :note: D4
  :file: sink_2.mov
- :note: E4
  :file: sink_3.mov
- :note: F4
  :file: sink_4.mov
# Pressure
- :note: G4
  :file: pressure.mov
- :note: G#4
  :file: pressure_2.mov
- :note: A4
  :file: pressure_3.mov
- :note: B4
  :file: pressure_4.mov
# Purple
- :note: C5
  :file: purple.mov
- :note: D5
  :file: purple_2.mov
- :note: E5
  :file: purple_3.mov
# Gloves
- :note: G5
  :file: gloves.mov
- :note: A5
  :file: gloves_2.mov
- :note: B5
  :file: gloves_3.mov
# Wasted
- :note: C6
  :file: wasted.mov
- :note: D6
  :file: wasted_2.mov
# Bird
- :note: E6
  :file: bird.mov
- :note: F6
  :file: bird_2.mov
- :note: F#6
  :file: bird_3.mov
# Aqua
- :note: G6
  :file: deep_vitae.mov
- :note: G#6
  :file: deep_vitae_2.mov
- :note: A6
  :file: aqua_mall.mov
- :note: A#6
  :file: aqua_mall_2.mov
- :note: B6
  :file: archer.mov
# Skeleton
- :note: C7
  :file: skeleton.mov
- :note: D7
  :file: skeleton_2.mov
# Dance
- :note: E7
  :file: dance.mov
- :note: F7
  :file: dance_2.mov
