- :note: C0
  :file: pressure.mov
- :note: D0
  :file: spider.mov
- :note: E0
  :file: skeleton.mov
- :note: F0
  :file: loop.mov
- :note: G0
  :file: bigbaby.mov
- :note: A0
  :file: wasted.mov
- :note: B0
  :file: dollar.mov
- :note: C1
  :file: swipe.mov
- :note: D1
  :file: theater.mov
- :note: E1
  :file: kissing.mov
- :note: F1
  :file: purple.mov
