#!/usr/bin/env ruby
$:.unshift(File.join("..", "lib"))

require "micromidi"

@output = UniMIDI::Output.gets

MIDI.using(@output) do

  # Initialize the Pittsburgh MIDI 2

  channel 0
  play "C1", 0.5

  channel 1
  play "C2", 0.5

end
