#!/usr/bin/env ruby
$:.unshift(File.join("..", "lib"))

require "micromidi"

@outputs = UniMIDI::Output.all.map(&:open)

MIDI.using(@outputs) do

  # Initialize the Pittsburgh MIDI 2

  channel 0
  play "C1", 0.5

  channel 1
  play "C2", 0.5

end
