windows:
  - name: liveset_right
    root: ~/workspace/liveset
    layout: tiled
    panes:
      - script/midi/init
      - script/vidplayer/client
      - script/vz/server
      - script/vz/hub
      - commands:
         - script/caffeinate
         - script/ableton/start
        focus: true
