windows:
  - name: liveset1
    root: ~/workspace/liveset
    layout: tiled
    panes:
      - script/vz/server
      - script/vz/hub
      - commands:
         - script/caffeinate
         - script/ableton/start
        focus: true
