windows:
  - name: startup_left
    root: ~/workspace/liveset
    layout: tiled
    panes:
      - script/vidplayer
      - commands:
         - /Applications/Ableton\ Live\ 9\ Suite.app/Contents/MacOS/Live assets/ableton/quick/setup_left.als
         - echo hi
        focus: true
