windows:
  - name: liveset_left
    root: ~/workspace/liveset
    layout: tiled
    panes:
      - script/vidplayer/listen
      - script/vidplayer/trigger
      - commands:
         - echo hi
        focus: true
