windows:
  - name: startup_right
    root: ~/workspace/liveset
    layout: tiled
    panes:
      - script/midi/init
      - script/vz/server
      - script/vz/hub
      - commands:
         - /Applications/Ableton\ Live\ 9\ Suite.app/Contents/MacOS/Live
         - echo hi
        focus: true
