windows:
  - name: liveset_right
    root: ~/workspace/liveset
    layout: tiled
    panes:
      - script/midi/init
      - script/vz/server
      - script/vz/hub
      - commands:
         - script/ableton/start
         - sleep 1
         - script/ableton/start
        focus: true
