windows:
  - name: startup_right
    root: ~/workspace/liveset
    layout: tiled
    panes:
      - script/midi/init
      - script/vz/server
      - script/vz/hub
      - commands:
         - echo hi
        focus: true
